# Generated by Django 4.1.1 on 2023-02-02 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Jewelry',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='jewelry',
        ),
    ]
