# Generated by Django 4.1.6 on 2023-04-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_site', '0008_remove_address_area_code_remove_address_building_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
