# Generated by Django 4.1.6 on 2023-04-17 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_site', '0009_remove_address_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
