# Generated by Django 4.1.6 on 2023-05-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_site', '0011_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='sub_total',
        ),
    ]
